spring.application.name=jpapersistance

# application.properties
spring.datasource.url=jdbc:postgresql://localhost:5432/jpahib
spring.datasource.username=jpahi
spring.datasource.password=jpahi

# JPA and Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# OAuth2 GITHUB configuration
spring.security.oauth2.client.registration.github.client-id=Ov23liYV9wKc7CkQ2xob
spring.security.oauth2.client.registration.github.client-secret=007b2ec769318bc9d19a7f3be0fd9edb61a315f7


# Google Login
spring.security.oauth2.client.registration.google.client-id=1059153777729-61nppjhh2d8286bcpev5sssiu8ir4bbt.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

# Default Spring Boot Security
spring.security.user.name=admin
spring.security.user.password=admin

#jwt secret key
jwt.secret=A8109E356C606EB46863B1984942F4C4E641CE2D7416855646AEB7860669FC76233ED9FE3C93A25C3874996E6CE6B093407B9E160BD1CF6BF1254983D44969282ADE73535248D19196278AEA5B2C3B070C6802BAF93A3AAFA49CE5D83B1809138A23BF90BA1E28BD9873608AEBAAEE9CDC767BF11C3DDFC5049F14A6227C1B29